name: adb_client_process
description: Desktop adb executable backend for adb_client.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.13.2

dependencies:
  adb_client:
    path: ../adb_client

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
